[
  {
    "code_line": "67:         self.df.index = np.arange(len(self.df))",
    "message": "Cannot assign to attribute \"index\" for class \"DataFrame\"\n\u00a0\u00a0\"ndarray[Any, dtype[signedinteger[Any]]]\" is not assignable to \"Index[Unknown]\"",
    "rule": "reportAttributeAccessIssue",
    "severity": "error",
    "source": "pyright"
  },
  {
    "code_line": "68:         self.df.index.name = 'id'",
    "message": "Cannot assign to attribute \"name\" for class \"NDArray[signedinteger[Any]]\"\n\u00a0\u00a0Attribute \"name\" is unknown",
    "rule": "reportAttributeAccessIssue",
    "severity": "error",
    "source": "pyright"
  },
  {
    "code_line": "123:         sns.histplot(ax = ax, data = pp.train[col], bins=100)",
    "message": "Argument of type \"Series[Unknown]\" cannot be assigned to parameter \"data\" of type \"DataSource | _DataSourceWideForm\" in function \"histplot\"\n\u00a0\u00a0Type \"Series[Unknown]\" is not assignable to type \"DataSource | _DataSourceWideForm\"\n\u00a0\u00a0\u00a0\u00a0\"Series[Unknown]\" is not assignable to \"DataFrame\"\n\u00a0\u00a0\u00a0\u00a0\"Series[Unknown]\" is incompatible with protocol \"SupportsDataFrame\"\n\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\"__dataframe__\" is not present\n\u00a0\u00a0\u00a0\u00a0\"Series[Unknown]\" is not assignable to \"Mapping[Any, Incomplete]\"\n\u00a0\u00a0\u00a0\u00a0\"Series[Unknown]\" is not assignable to \"None\"\n\u00a0\u00a0\u00a0\u00a0\"Series[Unknown]\" is not assignable to \"Mapping[Any, _Vector]\"\n\u00a0\u00a0\u00a0\u00a0\"Series[Unknown]\" is not assignable to \"Sequence[_Vector]\"\n  ...",
    "rule": "reportArgumentType",
    "severity": "error",
    "source": "pyright"
  }
]